/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import Controller.ControllerTeam;

/**
 *
 * @author USER
 */
public class FormTeam extends javax.swing.JFrame {
    public JTextField getTxtId_Team(){
        return txtIdTeam;
    }
    public JTextField getTxtNama_Team(){
        return txtNamaTeam;
    }
    public JTextField getTxtCeo(){
        return txtCeo;
    }
    public JTable getTabelTeam(){
        return tabelTeam;
    }
    public JButton getButtonInsert(){
        return btnTambahTeam;
    }
    public JButton getButtonUpdate(){
        return btnUpdateTeam;
    }
    public JButton getButtonDetele(){
        return btnHapusTeam;
    }
    public JButton getButtonReset(){
        return btnBatalTeam;
    }
    
    ControllerTeam cbt;
    /**
     * Creates new form FormTeam
     */
    public FormTeam() {
        initComponents();
        setLocationRelativeTo(null);
        cbt = new ControllerTeam(this);
        cbt.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaTeam = new javax.swing.JTextField();
        txtCeo = new javax.swing.JTextField();
        btnTambahTeam = new javax.swing.JButton();
        btnHapusTeam = new javax.swing.JButton();
        btnUpdateTeam = new javax.swing.JButton();
        btnBatalTeam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTeam = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtIdTeam = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnCredits = new javax.swing.JButton();
        btnKlasemen = new javax.swing.JButton();
        btnTeam = new javax.swing.JButton();
        btnMatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TEAM LIST");

        jLabel2.setText("NAMA TEAM :");

        btnTambahTeam.setText("➕");
        btnTambahTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTeamActionPerformed(evt);
            }
        });

        btnHapusTeam.setText("➖");
        btnHapusTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTeamActionPerformed(evt);
            }
        });

        btnUpdateTeam.setText("🗘");
        btnUpdateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTeamActionPerformed(evt);
            }
        });

        btnBatalTeam.setText("✖");
        btnBatalTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTeamActionPerformed(evt);
            }
        });

        tabelTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Team", "CEO"
            }
        ));
        tabelTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTeamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTeam);

        jLabel3.setText("NAMA CEO :");

        txtIdTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdTeam.setPreferredSize(new java.awt.Dimension(0, 0));

        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCredits.setText("Credits");
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });

        btnKlasemen.setText("Klasemen");
        btnKlasemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlasemenActionPerformed(evt);
            }
        });

        btnTeam.setText("Team");

        btnMatch.setText("Match");
        btnMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKlasemen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeam)
                .addGap(18, 18, 18)
                .addComponent(btnMatch)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCeo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahTeam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusTeam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateTeam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatalTeam))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtIdTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCredits)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnKlasemen)
                    .addComponent(btnTeam)
                    .addComponent(btnMatch))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahTeam)
                            .addComponent(btnHapusTeam)
                            .addComponent(btnUpdateTeam)
                            .addComponent(btnBatalTeam))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCredits)
                    .addComponent(txtIdTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTeamActionPerformed
        // TODO add your handling code here:
        cbt.insert();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnTambahTeamActionPerformed

    private void btnHapusTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTeamActionPerformed
        // TODO add your handling code here:
        cbt.delete();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnHapusTeamActionPerformed

    private void btnUpdateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTeamActionPerformed
        // TODO add your handling code here:
        cbt.update();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnUpdateTeamActionPerformed

    private void btnBatalTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTeamActionPerformed
        // TODO add your handling code here:
        cbt.reset();
    }//GEN-LAST:event_btnBatalTeamActionPerformed

    private void tabelTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTeamMouseClicked
        // TODO add your handling code here:
        int row = tabelTeam.getSelectedRow();
        cbt.isiField(row);
    }//GEN-LAST:event_tabelTeamMouseClicked

    private void btnKlasemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlasemenActionPerformed
        // TODO add your handling code here:
        KlasemenAdmin klas = new KlasemenAdmin();
        klas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKlasemenActionPerformed

    private void btnMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchActionPerformed
        // TODO add your handling code here:
        TeamMatch match = new TeamMatch();
        match.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Landing land = new Landing();
        land.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
        // TODO add your handling code here:
        Credits cred = new Credits();
        cred.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalTeam;
    private javax.swing.JButton btnCredits;
    private javax.swing.JButton btnHapusTeam;
    private javax.swing.JButton btnKlasemen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMatch;
    private javax.swing.JButton btnTambahTeam;
    private javax.swing.JButton btnTeam;
    private javax.swing.JButton btnUpdateTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTeam;
    private javax.swing.JTextField txtCeo;
    private javax.swing.JTextField txtIdTeam;
    private javax.swing.JTextField txtNamaTeam;
    // End of variables declaration//GEN-END:variables

}
