    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ControllerMatch;
import Model.TabelModelMatch;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class TeamMatch extends javax.swing.JFrame {
    public JTable getTabelMatch(){
        return tabelMatch;
    }
    public JTextField getTxtId_Match(){
        return txtIdMatch;
    }
    public JComboBox<String> getCombNama_Team1(){
        return combNamaTeam1;
    }
    public JComboBox<String> getCombNama_Team2(){
        return combNamaTeam2;
    }
    public JTextField getTxtGame1(){
        return txtGame1;
    }
    public JTextField getTxtGame2(){
        return txtGame2;
    }
    public JTextField getTxtTanggal(){
        return txtTanggal;
    }
    public JRadioButton getBoolMatch1(){
        return boolMatch1;
    }
    public JRadioButton getBoolMatch2(){
        return boolMatch2;
    }
    
    ControllerMatch cbt;
    /**
     * Creates new form TeamMatch
     */
    public TeamMatch() {
        initComponents();
        setLocationRelativeTo(null);
        cbt = new ControllerMatch(this);
        cbt.isiComboTeam();
        cbt.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupBool = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMatch = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnTeam = new javax.swing.JButton();
        btnKlasemen = new javax.swing.JButton();
        btnCredits = new javax.swing.JButton();
        combNamaTeam1 = new javax.swing.JComboBox<>();
        combNamaTeam2 = new javax.swing.JComboBox<>();
        txtTanggal = new javax.swing.JTextField();
        txtGame1 = new javax.swing.JTextField();
        txtGame2 = new javax.swing.JTextField();
        boolMatch2 = new javax.swing.JRadioButton();
        boolMatch1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTambahTeam = new javax.swing.JButton();
        btnHapusTeam = new javax.swing.JButton();
        btnUpdateTeam = new javax.swing.JButton();
        btnBatalTeam = new javax.swing.JButton();
        txtIdMatch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelMatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Team A", "Game A", "Tanggal", "Game B", "Nama Team B"
            }
        ));
        tabelMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMatchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMatch);
        if (tabelMatch.getColumnModel().getColumnCount() > 0) {
            tabelMatch.getColumnModel().getColumn(4).setHeaderValue("Nama Team B");
        }

        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnJadwal.setText("Match");

        btnTeam.setText("Team");
        btnTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeamActionPerformed(evt);
            }
        });

        btnKlasemen.setText("Klasemen");
        btnKlasemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlasemenActionPerformed(evt);
            }
        });

        btnCredits.setText("Credits");

        btnGroupBool.add(boolMatch2);

        btnGroupBool.add(boolMatch1);

        jLabel1.setText("Nama Team");

        jLabel2.setText("Nama Team");

        jLabel3.setText("Game");

        jLabel4.setText("Game");

        jLabel5.setText("Tanggal");

        jLabel6.setText("Validasi");

        jLabel7.setText("Validasi");

        btnTambahTeam.setText("➕");
        btnTambahTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTeamActionPerformed(evt);
            }
        });

        btnHapusTeam.setText("➖");
        btnHapusTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTeamActionPerformed(evt);
            }
        });

        btnUpdateTeam.setText("🗘");
        btnUpdateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTeamActionPerformed(evt);
            }
        });

        btnBatalTeam.setText("✖");
        btnBatalTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKlasemen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTeam)
                                .addGap(18, 18, 18)
                                .addComponent(btnJadwal)
                                .addGap(269, 269, 269)
                                .addComponent(btnLogout))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(combNamaTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(boolMatch1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6)
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel3)
                                            .addGap(64, 64, 64)
                                            .addComponent(jLabel5)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(47, 47, 47)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(boolMatch2)
                                            .addGap(29, 29, 29)
                                            .addComponent(combNamaTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel7)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel2))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnTambahTeam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnHapusTeam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUpdateTeam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBatalTeam)
                                    .addGap(235, 235, 235))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCredits)
                        .addGap(274, 274, 274))))
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(txtIdMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKlasemen)
                    .addComponent(btnTeam)
                    .addComponent(btnJadwal)
                    .addComponent(btnLogout))
                .addGap(17, 17, 17)
                .addComponent(txtIdMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combNamaTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combNamaTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boolMatch2))
                    .addComponent(boolMatch1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahTeam)
                    .addComponent(btnHapusTeam)
                    .addComponent(btnUpdateTeam)
                    .addComponent(btnBatalTeam))
                .addGap(30, 30, 30)
                .addComponent(btnCredits)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Landing land = new Landing();
        land.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamActionPerformed
        // TODO add your handling code here:
        FormTeam formT = new FormTeam();
        formT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTeamActionPerformed

    private void btnKlasemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlasemenActionPerformed
        // TODO add your handling code here:
        KlasemenAdmin klas = new KlasemenAdmin();
        klas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKlasemenActionPerformed

    private void btnTambahTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTeamActionPerformed
        // TODO add your handling code here:
        cbt.insert();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnTambahTeamActionPerformed

    private void btnHapusTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTeamActionPerformed
        // TODO add your handling code here:
        cbt.delete();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnHapusTeamActionPerformed

    private void btnUpdateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTeamActionPerformed
        // TODO add your handling code here:
        cbt.update();
        cbt.isiTable();
        cbt.reset();
    }//GEN-LAST:event_btnUpdateTeamActionPerformed

    private void btnBatalTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTeamActionPerformed
        // TODO add your handling code here:
        cbt.reset();
    }//GEN-LAST:event_btnBatalTeamActionPerformed

    private void tabelMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMatchMouseClicked
        // TODO add your handling code here:
        int row = tabelMatch.getSelectedRow();
        cbt.isiField(row);
    }//GEN-LAST:event_tabelMatchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamMatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boolMatch1;
    private javax.swing.JRadioButton boolMatch2;
    private javax.swing.JButton btnBatalTeam;
    private javax.swing.JButton btnCredits;
    private javax.swing.ButtonGroup btnGroupBool;
    private javax.swing.JButton btnHapusTeam;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKlasemen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambahTeam;
    private javax.swing.JButton btnTeam;
    private javax.swing.JButton btnUpdateTeam;
    private javax.swing.JComboBox<String> combNamaTeam1;
    private javax.swing.JComboBox<String> combNamaTeam2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMatch;
    private javax.swing.JTextField txtGame1;
    private javax.swing.JTextField txtGame2;
    private javax.swing.JTextField txtIdMatch;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
